services:
  postgres:
    image: postgres:16-alpine
    container_name: nexlog-postgres
    environment:
      POSTGRES_DB: nexlog_mercadao
      POSTGRES_USER: nexlog
      POSTGRES_PASSWORD: nexlog123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexlog -d nexlog_mercadao"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
